//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitFlyWingStatWithGraphInCSharpdotNet.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FruitFlyDBEntities : DbContext
    {
        public FruitFlyDBEntities()
            : base("name=FruitFlyDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Wing> Wings { get; set; }
        public virtual DbSet<WingCoordinate> WingCoordinates { get; set; }
        public virtual DbSet<WIngProject> WIngProjects { get; set; }
    }
}
