//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitFlyWingStatWithGraphInCSharpdotNet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wing()
        {
            this.WingCoordinates = new HashSet<WingCoordinate>();
        }
    
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime FileDate { get; set; }
        public System.DateTime ImportDate { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Perimeter { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Length { get; set; }
    
        public virtual WIngProject WIngProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WingCoordinate> WingCoordinates { get; set; }
    }
}
