//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitFlyWingStatWithGraphInCSharpdotNet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIngProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WIngProject()
        {
            this.Wings = new HashSet<Wing>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public System.DateTime createdAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wing> Wings { get; set; }
    }
}
