//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitFlyWingStatWithGraphInCSharpdotNet.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WingCoordinate
    {
        public int Id { get; set; }
        public int WingId { get; set; }
        public int x { get; set; }
        public int y { get; set; }
    
        public virtual Wing Wing { get; set; }
    }
}
